### ISSUE TITLE
The Container Apps Environment failed to provision

### ISSUE THREAD

**Issue by mquile1209** [microsoft/azure-container-apps#1112]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I have an environment with 9 container apps that has been running for almost a year. Last week I went to deploy a container and it showed that the container app environment failed to provision. The only solution provided was to delete the environment and redeploy all of containers. 

I was not able to find a cause in any of the health reports or logs.

### Steps to reproduce

I can't reproduce as this happened automatically on the Azure backend on a Sunday when no one was working.

### Additional context
This issue was seen in the portal and the CLI.

**Comment by simonjj** [comment]
Thank you for reaching out @mquile1209. When you say the environment failed to provision did you mean the container app within the environment. Usually once an environment runs it doesn't get recreated when you deploy a new container or app. Also would you be able to share the resource URL or name, location and resource group for the environment. That'll allow us to take a look at the backend logs to see if we find the cause of your issue.

**Comment by mquile1209** [comment]
> Thank you for reaching out @mquile1209. When you say the environment failed to provision did you mean the container app within the environment. Usually once an environment runs it doesn't get recreated when you deploy a new container or app. Also would you be able to share the resource URL or name, location and resource group for the environment. That'll allow us to take a look at the backend logs to see if we find the cause of your issue.

No the container environment was somehow reprovisioned. I saw it on the monitoring dashboard. I deleted the environment as I had to recreate it since it was needed by our devs. This screenshot was the only indicator that something had happened to the environment.

![2024-02-20_09-52-04](https://github.com/microsoft/azure-container-apps/assets/131384545/96a97f89-7586-4195-bc29-bb804cf72163)

**Comment by simonjj** [comment]
Thank you for this detail. Was the environment re-provisioned by you? Or are you suggesting a control plane process did so? Could it be that the app was scaled to zero and came back after some delay? We will need something to help find the app could you please email your details to "Azure Container Apps Support" <acasupport@microsoft.com>.

**Comment by chriswue** [comment]
I would like to add that this also happened for us a few days ago. In our case the location is Australia East. I have opened a support ticket with Microsoft.

**Comment by lewis-pilot** [comment]
Hi,

I would like to add that I am experiencing the same issue in Australia East as @chriswue is above. I can create container applications through the UI after although since I generate everything via terraform it blocks our deployment pipeline.

This tends to only happen to me when I specify internal/subnet with the consumption plan. It works when the following has been enabled.

**Comment by praneetloke** [comment]
This is exactly the problem I reported in https://github.com/microsoft/azure-container-apps/issues/868. MS support claimed that the VNET for the environment was moved out of the subscription but it was not. Like @mquile1209 my environment was running for over a year when one day I started experiencing this problem. Then again, out of nowhere, after about a month of no resolution from support the error went away on its own. I did nothing to fix it. In fact, I had created a new environment and started to deploy containers to it while the original environment wouldn't let me update even existing containers.

**Comment by mquile1209** [comment]
My environment is the same as @praneetloke. Consumption only, internal only using a VNET. I have sent an email as requested.

**Comment by chriswue** [comment]
Our container app environment just uses consumption only tier with no explicit VNET attached (i.e. fully default configuration).

**Comment by chinadragon0515** [comment]
@praneetloke do you still see issues? If yes, can you help to send env information to [acasupport@microsoft.com](mailto:acasupport@microsoft.com) so I can check more.

@chriswue I have replied your email, let's work via email.

**Comment by sridraj** [comment]
We also started having the same issue today. Our container app is in West Europe Region. Container environment is attached to a VNET with external ingress enabled. We have 12 apps running inside that environment, although they are working as expected but our release process is blocked because of this issue.

**Comment by stweb1963** [comment]
We have been seeing the same issue but the 'Quick' solution is to add a tag to the Container App Environment
This cause the CA Env to return to a Provisioned State and then you should be able to proceed.

See #1113

**Comment by charris-msft** [comment]
@simonjj - 
I'm seeing similar problems today trying to create ACA environments and subsequently apps in eastus:

Sorry you don't get the pretty colors, but there is the Terminal output:
```

{
  "id": "/subscriptions/2554f64d-0419-4e39-8121-5e01270578ea/resourceGroups/charris-mb-2",
  "location": "eastus",
  "managedBy": null,
  "name": "charris-mb-2",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null,
  "type": "Microsoft.Resources/resourceGroups"
}
PS C:\git\ai\metabase> ^C
PS C:\git\ai\metabase> az account show --query "{subscriptionId:id, subscriptionName:name}"
{
  "subscriptionId": "2554f64d-0419-4e39-8121-5e01270578ea",
  "subscriptionName": "ScottHunter_TeamDemoSub"
}
PS C:\git\ai\metabase> ^C
PS C:\git\ai\metabase> az containerapp env create --resource-group charris-mb-2 --name myEnvironment --location eastus
No Log Analytics workspace provided.
Generating a Log Analytics workspace with name "workspace-charrismb2YIbL"
\ Running ..The command failed with an unexpected error. Here is the traceback:
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/containerapp/containerapp_env_decorator.py", line 146, in create     
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/containerapp/_clients.py", line 474, in create
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/containerapp/_clients.py", line 62, in poll_status
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 1004, in send_raw_request
azure.cli.core.azclierror.HTTPError: Service Unavailable(<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body {font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>AzureResourceManager</title></head><body><div id='content'><div id='message'><h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p></div><div id='errorref'><span>Ref A: 7D5B3E992F1F44B6B08BF90447C2406F Ref B: CO6AA3150217045 Ref C: 2024-03-08T18:49:26Z</span></div></div></body></html>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 729, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/containerapp/_client_factory.py", line 28, in _polish_bad_errors     
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 698, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/containerapp/custom.py", line 836, in create_managed_environment     
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/containerapp/containerapp_env_decorator.py", line 149, in create     
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/containerapp/_client_factory.py", line 45, in handle_raw_exception   
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues     
PS C:\git\ai\metabase> az containerapp env create --resource-group charris-mb-2 --name myEnvironment --location eastus
No Log Analytics workspace provided.
Generating a Log Analytics workspace with name "workspace-charrismb2HeP3"
(ManagedEnvironmentOperationInProgress) Cannot modify Container Apps environment myEnvironment because another operation is in progress.
PS C:\git\ai\metabase> ^C                                                             
PS C:\git\ai\metabase> az containerapp show --resource-group charris-mb-2 --name myMetabase --query 'data.properties.address.fqdn' -o tsv
(ResourceNotFound) The Resource 'Microsoft.App/containerApps/myMetabase' under resource group 'charris-mb-2' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
PS C:\git\ai\metabase> az containerappenv show --resource-group charris-mb-2 --name myMetabase                                              
'containerappenv' is misspelled or not recognized by the system.
Did you mean 'containerapp' ?

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs
PS C:\git\ai\metabase> az containerapp env show --resource-group charris-mb-2 --name myMetabase
(ResourceNotFound) The Resource 'Microsoft.App/managedEnvironments/myMetabase' under resource group 'charris-mb-2' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
PS C:\git\ai\metabase> az containerapp env create --resource-group charris-mb-2 --name myEnvironment --location eastus
No Log Analytics workspace provided.
Generating a Log Analytics workspace with name "workspace-charrismb2c3ZU"
(ManagedEnvironmentOperationInProgress) Cannot modify Container Apps environment myEnvironment because another operation is in progress.
PS C:\git\ai\metabase> az containerapp env create --resource-group charris-mb-2 --name myEnvironment --location eastus
No Log Analytics workspace provided.
Generating a Log Analytics workspace with name "workspace-charrismb2uVjh"
(ManagedEnvironmentOperationInProgress) Cannot modify Container Apps environment myEnvironment because another operation is in progress.
PS C:\git\ai\metabase> ^C
PS C:\git\ai\metabase> az containerapp env delete --resource-group charris-mb-2 --name myEnvironment
Are you sure you want to perform this operation? (y/n): y                             
Containerapp environment successfully deleted
PS C:\git\ai\metabase> az containerapp env create --resource-group charris-mb-2 --name myEnvironment --location eastus
No Log Analytics workspace provided.
Generating a Log Analytics workspace with name "workspace-charrismb2He7U"
(ManagedEnvironmentScheduledForDelete) The environment 'myEnvironment' is under deletion. Please retry the creation with new name or wait for the deletion completed.       
PS C:\git\ai\metabase> az containerapp env create --resource-group charris-mb-2 --name myEnvironment --location eastus
No Log Analytics workspace provided.
Generating a Log Analytics workspace with name "workspace-charrismb2vtuo"
(ManagedEnvironmentScheduledForDelete) The environment 'myEnvironment' is under deletion. Please retry the creation with new name or wait for the deletion completed.       
PS C:\git\ai\metabase> az containerapp env create --resource-group charris-mb-2 --name myEnvironment --location eastus
No Log Analytics workspace provided.
Generating a Log Analytics workspace with name "workspace-charrismb24gB3"
(ManagedEnvironmentScheduledForDelete) The environment 'myEnvironment' is under deletion. Please retry the creation with new name or wait for the deletion completed.       
PS C:\git\ai\metabase> az containerapp env create --resource-group charris-mb-2 --name myEnvironment --location eastus
No Log Analytics workspace provided.
Generating a Log Analytics workspace with name "workspace-charrismb2sbNy"
(ManagedEnvironmentScheduledForDelete) The environment 'myEnvironment' is under deletion. Please retry the creation with new name or wait for the deletion completed.       
PS C:\git\ai\metabase> ^C
PS C:\git\ai\metabase> az containerapp env create --resource-group charris-mb-2 --name myEnvironment2 --location eastus
No Log Analytics workspace provided.
Generating a Log Analytics workspace with name "workspace-charrismb2v1Uw"
Containerapp environment creation in progress. Please monitor the creation using `az containerapp env show -n myEnvironment2 -g charris-mb-2`
{
  "id": "/subscriptions/2554f64d-0419-4e39-8121-5e01270578ea/resourceGroups/charris-mb-2/providers/Microsoft.App/managedEnvironments/myEnvironment2",
  "location": "East US",
  "name": "myEnvironment2",
  "properties": {
    "appLogsConfiguration": {
      "destination": "log-analytics",
      "logAnalyticsConfiguration": {
        "customerId": "7a259451-9d13-4954-84aa-71e308611f6b",
        "sharedKey": null
      }
    },
    "customDomainConfiguration": {
      "certificatePassword": null,
      "certificateValue": null,
      "customDomainVerificationId": "F4E3370D922718D36A215A0CAD8775EC78DAE97CF1B32E122308FFCCA3C28F7E",
      "dnsSuffix": null,
      "expirationDate": null,
      "subjectName": null,
      "thumbprint": null
    },
    "daprAIConnectionString": null,
    "daprAIInstrumentationKey": null,
    "daprConfiguration": {
      "version": "1.11.6"
    },
    "defaultDomain": "mangopebble-19c68396.eastus.azurecontainerapps.io",
    "eventStreamEndpoint": "https://eastus.azurecontainerapps.dev/subscriptions/2554f64d-0419-4e39-8121-5e01270578ea/resourceGroups/charris-mb-2/managedEnvironments/myEnvironment2/eventstream",
    "infrastructureResourceGroup": null,
    "kedaConfiguration": {
      "version": "2.12.0"
    },
    "peerAuthentication": {
      "mtls": {
        "enabled": false
      }
    },
    "provisioningState": "Waiting",
    "staticIp": "4.156.109.50",
    "vnetConfiguration": null,
    "workloadProfiles": [
      {
        "name": "Consumption",
        "workloadProfileType": "Consumption"
      }
    ],
    "zoneRedundant": false
  },
  "resourceGroup": "charris-mb-2",
  "systemData": {
    "createdAt": "2024-03-08T19:35:30.4222606",
    "createdBy": "charris@microsoft.com",
    "createdByType": "User",
    "lastModifiedAt": "2024-03-08T19:35:30.4222606",
    "lastModifiedBy": "charris@microsoft.com",
    "lastModifiedByType": "User"
  },
  "type": "Microsoft.App/managedEnvironments"
}
PS C:\git\ai\metabase> ^C
PS C:\git\ai\metabase> az containerapp create --resource-group charris-mb-2 --name myMetabase --environment myEnvironment2 --image metabase/metabase --target-port 3000
Usage error: must specify --ingress with --target-port
PS C:\git\ai\metabase> ^C
PS C:\git\ai\metabase> az containerapp create --resource-group charris-mb-2 --name myMetabase --environment myEnvironment2 --image metabase/metabase --target-port 3000 --ingress External
(ManagedEnvironmentNotProvisioned) The environment '/subscriptions/2554f64d-0419-4e39-8121-5e01270578ea/resourceGroups/charris-mb-2/providers/Microsoft.App/managedEnvironments/myEnvironment2' has not been provisioned successfully.
PS C:\git\ai\metabase> az containerapp create --resource-group charris-mb-2 --name myMetabase --environment myEnvironment2 --image metabase/metabase --target-port 3000 --ingress External
(ManagedEnvironmentNotProvisioned) The environment '/subscriptions/2554f64d-0419-4e39-8121-5e01270578ea/resourceGroups/charris-mb-2/providers/Microsoft.App/managedEnvironments/myEnvironment2' has not been provisioned successfully.
PS C:\git\ai\metabase> ^C
PS C:\git\ai\metabase> az containerapp up --resource-group charris-mb-3 --name myMetabase3 --environment myEnvironment3 --image metabase/metabase --target-port 3000 --ingress External 
Creating resource group 'charris-mb-3'
Creating ContainerAppEnvironment 'myEnvironment3' in resource group charris-mb-3
No Log Analytics workspace provided.
Generating a Log Analytics workspace with name "workspace-charrismb3ITuV"
Creating Containerapp myMetabase3 in resource group charris-mb-3
(ManagedEnvironmentNotProvisioned) The environment '/subscriptions/2554f64d-0419-4e39-8121-5e01270578ea/resourceGroups/charris-mb-3/providers/Microsoft.App/managedEnvironments/myEnvironment3' has not been provisioned successfully.
```

**Comment by chinadragon0515** [comment]
@sridraj  do you still see issues? If yes, can you help to send env information to [acasupport@microsoft.com](mailto:acasupport@microsoft.com) so I can check more.

@charris-msft  I checked your env, it is deployed to canary region central us euap which has an outage at that time due to dependent service unavailable, you can retry the deployment.

**Comment by StianSaeten** [comment]
We experienced the same issue on Friday 8th of March when we did an incremental deployment with only tag changes (some properties was reset, but they always gets reset to default since it is not assigned any value in our template). I have tried the "quick fix" and changed a tag from the portal, but it is stuck failed to provision. Also tried redeploy with the Bicep template. 

It is a managed environment with internal vnet integration in west Europe. 

Even if it is a test environment, I do not want to delete and redeploy. (Which would have been the quick fix.) The containers are running fine (except we can't do any changes to them since the environment is in failed state) and have a crucial role internally in the company.

I have created a Microsoft support ticket, but is anyone has a tips or solution to solve this, it would be much appreciated.

**Comment by chinadragon0515** [comment]
I have investigated several issues reported via email, I have not seen common issue yet. Several notes I want to share,
1. If you are creating new container app consumption only environment, and failed, it is normal due to vNet configuration issues, refer to https://learn.microsoft.com/en-us/azure/container-apps/firewall-integration?tabs=consumption-only for detail network requirements.
We also show the detail error in the deployment error property of the environment.
In the meanwhile, I strongly recommend to create workload profile environment (you can only use consumption workload profile), it will give you more flexibility on network configuration.

3. If you fail to update existing environment, you can send your env information to [acasupport@microsoft.com](mailto:acasupport@microsoft.com) so we can check more. And in the meanwhile, you can retry the update to see whether it is transient issue or persistent issue, also note update existing environment failed will not impact existing workload.

4. If you fail to create or update container apps in the environment, this is normal related to container app configuration, the log always have the details about the error, and let us know if you do not see the error.

**Comment by chinadragon0515** [comment]
@StianSaeten  can you help to send you enviroment information and ticket information to [acasupport@microsoft.com](mailto:acasupport@microsoft.com) so we can check more.

**Comment by sridraj** [comment]
Yes.. the issue got resolved.. I added a temporary tag via portal.. and then the container environment went back to successful provisioned state.

**Comment by chriswue** [comment]
Same here, just adding a tag got it out of the bad state. Seems a bit random

**Comment by jordanchang** [comment]
Just wanted to say I am facing this today with WESTUS only. My other region, WESTUS2, is running fine.

**Comment by dsbahr** [comment]
I managed to reproduce this on my end. I had a container app environment deployed with bicep. It was set to point to a subnet in our own vnet and I also had a workload profile defined for the environment. 

I then recently changed the container app environment, so no workload profiles were defined (meaning it would run Consumption plan only), deleted the container app environment, and redeployed the template again.

Now the container app fails to provision. If I add the workload profile again, it does provision. 

So it seems that I cannot provision a container app environment, integrating it into an existing vnet, if it is a Consumption plan only environment. 

According to the documentation here https://learn.microsoft.com/en-us/azure/container-apps/vnet-custom?tabs=bash%2Cazure-cli&pivots=azure-portal I should be able to do so.

**Comment by jvalteren** [comment]
> Same here, just adding a tag got it out of the bad state. Seems a bit random

For whom it may concern, I just ran into a similar issue.

**Context**
Container app environment was running happily with 12 apps. I had to change the access mode on one of the file shares (I'm using Terraform), but it was reporting that it was still in use (which was correct). So I did a targeted destroy of the container app that was using it and tried to re-run the entire Terraform plan which would reprovision the destroyed container app and also included the change in file share access mode. This is what resulted in the error `ManagedEnvironmentNotProvisioned: The environment '/subscriptions/***/resourceGroups/***/providers/Microsoft.App/managedEnvironments/cae-prd' has not been provisioned successfully.`

**Solution**
Following suggestions by @sridraj and @chriswue, I edited the tags (added one), which reset the provisioning state back to `Success`. A subsequent Terraform reprovisioning of the destroyed container app and change in the file share access mode worked correctly.

**Comment by hungdhm-0574** [comment]
@chinadragon0515
I had the same issue 2 days ago. My app still works fine, the last revision I created in 26/08/2024. But after that, but after that, I was unable to create new revisions anymore.

I emailed you my subscription error already. Wait for your response, thank you very much.

**Comment by hungdhm-0574** [comment]
Updated:
@chinadragon0515
Thanks, ACA support team, my ACA app is back to work again.

The problem is Subnet setting (which use for Container environment)

Emailed from Vincent He of ACA support team:
`For **consumption only** environment, you should **NOT** set delegation for the subnet.
For **workload** profile environment, you **must** set delegation to Microsoft.app/environments.

The difference is how the IP of subnet is managed. Consumption only environment and workload profile environment use different way to manage the subnet IPs.`

So, if your ACA meet the issue suddenly, you should check your Subnet config, and set delegation to null your your subnet **( for consumption only environment)**

**Comment by jaliyaudagedara** [comment]
I am facing this issue:

1. Created a new container app (by default `Environment type: Workload profiles` and no option to change it to `Consumption`)
   1. Networking
       1. Use your own virtual network: yes
       2. Created a new subnet in an existing VNet and `Virtual IP: Internal`
2. Tried deploying

![image](https://github.com/user-attachments/assets/fed54ae8-138d-449a-b217-f47d54625eb6)

```
 az containerapp update `                                                                                                                                                                  
  --name <container-app> `
  --resource-group rg-xxx-xxxxx-xxx-001 `
  --image '<image>' `
  --min-replicas 1 `
  --max-replicas 1
```
Output
```
The behavior of this command has been altered by the following extension: containerapp
{
  "id": "/subscriptions/<subscriptionId>/resourceGroups/rg-xxx-xxxxx-xxx-001/providers/Microsoft.App/containerapps/<container-app>",
  "identity": {
    "type": "None"
  },
  "kind": "containerapps",
  "location": "East US 2",
  "name": "<container-app>",
  "properties": {
    "configuration": {
      "activeRevisionsMode": "Single",
      "dapr": null,
      "identitySettings": [],
      "ingress": null,
      "maxInactiveRevisions": 100,
      "registries": null,
      "runtime": null,
      "secrets": null,
      "service": null
    },
    "customDomainVerificationId": "6D856BC35D493EED9148F0118DEDE32FC8AAC8B4530A7919A8436444AF907AEC",
    "delegatedIdentities": [],
    "environmentId": "/subscriptions/<subscriptionId>/resourceGroups/rg-xxx-xxxxx-xxx-001/providers/Microsoft.App/managedEnvironments/<container-app-environment>",
    "eventStreamEndpoint": "https://eastus2.azurecontainerapps.dev/subscriptions/<subscriptionId>/resourceGroups/rg-xxx-xxxxx-xxx-001/containerApps/<container-app>/eventstream",
    "latestReadyRevisionName": "<container-app>--qrivu4c",
    "latestRevisionFqdn": "",
    "latestRevisionName": "<container-app>--qrivu4c",
    "managedEnvironmentId": "/subscriptions/<subscriptionId>/resourceGroups/rg-xxx-xxxxx-xxx-001/providers/Microsoft.App/managedEnvironments/<container-app-environment>",
    "outboundIpAddresses": null,
    "patchingMode": "Automatic",
    "provisioningState": "Failed",
    "runningStatus": "Running",
    "template": {
      "containers": [
        {
          "image": "mcr.microsoft.com/k8se/quickstart:latest",
          "imageType": "ContainerImage",
          "name": "simple-hello-world-container",
          "resources": {
            "cpu": 0.25,
            "ephemeralStorage": "1Gi",
            "memory": "0.5Gi"
          }
        }
      ],
      "initContainers": null,
      "revisionSuffix": "",
      "scale": {
        "maxReplicas": 10,
        "minReplicas": 0,
        "rules": null
      },
      "serviceBinds": null,
      "terminationGracePeriodSeconds": null,
      "volumes": null
    },
    "workloadProfileName": "Consumption"
  },
  "resourceGroup": "rg-xxx-xxxxx-xxx-001",
  "type": "Microsoft.App/containerApps"
}
'replicaSet' is not recognized as an internal or external command,
operable program or batch file.
'retrywrites' is not recognized as an internal or external command,
operable program or batch file.
'maxIdleTimeMS' is not recognized as an internal or external command,
operable program or batch file.
'appName' is not recognized as an internal or external command,
operable program or batch file.
```

In the output:
![image](https://github.com/user-attachments/assets/6010a444-ebd1-4109-92c5-653e811c60fc)

Subnet is delegated to `Microsoft.App/environments`.

**Comment by johnLwith** [comment]
> Updated: [@chinadragon0515](https://github.com/chinadragon0515) Thanks, ACA support team, my ACA app is back to work again.
> 
> The problem is Subnet setting (which use for Container environment)
> 
> Emailed from Vincent He of ACA support team:
> 
> ```
> For **consumption only** environment, you should **NOT** set delegation for the subnet.
> For **workload** profile environment, you **must** set delegation to Microsoft.app/environments.
> 
> The difference is how the IP of subnet is managed. Consumption only environment and workload profile environment use different way to manage the subnet IPs.
> ```
> 
> So, if your ACA meets the issue suddenly, you should check your Subnet config, and set delegation to null for your subnet **( for consumption-only environment)**. Then "restart" the Container Apps Environment by changing any dummy config of the Container Apps Environment like adding or removing a Tags.
> 
> Then try to create a new revision again.

what's the root cause?

**Comment by edonosotti** [comment]
Same problem here. The Container App Environment and the Container Apps in it have been up and running for a long time.
The apps still work fine, but the environment says "The Container App Environment failed to provision" and every attempt to update it via Terraform fails.

Reading the comments here it sounds like these has been going for over a year 🤦🏻‍♂️
Actually I submitted other Azure-related issues more or less 2 years ago that, to this day, remain unanswered.

**Comment by svickers** [comment]
Same problem here today, environment been up for a while, deployments were working as of July 3rd and now nothing can be deployed.  Using bicep for deployments our dev ACE is working fine.

**Comment by nick-laws** [comment]
Having the same issue. Several Apps are still running fine, but any deployment/revision fails. Was also able to remove an App, just can't add or update. Trying the subnet delegation trick now. Though when we first created the environment it wouldn't work without that delegation so not sure if that'll do the trick.

**Comment by edonosotti** [comment]
@svickers @nick-laws the add-remove tag trick explained above worked for us.
That said, it's clear that there are issues at platform level.

**Comment by svickers** [comment]
@edonosotti Unfortunately adding or removing tags wasn't working for us and it was still showing in a failed state.  I enabled System Assigned Identity and that seems to have done the trick of restarting the environment so now we can deploy again.

**Comment by christopherenriquez** [comment]
Applying tags and system-assigned identity didn't work on our setup. We had a working setup for about a year, and suddenly we have this issue 😅, the last resort is to re-create the resource 🤦‍♂️

**Comment by esciullo** [comment]
I have the same issue. The trick of add-remove identity or tags doesn't work anymore.

**Comment by svickers** [comment]
The suggestion from Azure Support was to make sure to use system managed identity and also verify that the identity has secrets read access to our key vault.  I believe this is for our custom domain cert, but odd because that is a cert and not a secret.  Anyway we did that and it worked for about 2 weeks but just popped up again last Friday.  Our continued recurring solution is to turn off system identity and then turn it back on.

>Confirm the Identity in Use
Please ensure that the environment is now using a System-Assigned Managed Identity (SAMI) and that references to the previous User-Assigned Managed Identity (UAMI) have been removed.
 

>Audit Key Vault Access
Double-check that the active identity has the necessary secrets/get permission on the 'xxxxx' vault.

**Comment by seciq** [comment]
I have the same issue with 2 environments. As pointed by @hungdhm-0574 the delegation to Microsoft.app/environments in VNET is the most likely cause. I've checked and removed this delegation in the VNET for both environments. 

The trick of add-remove identity or tags _only worked for one environment_. For the other environment does not work and we're stuck.

I would have deleted and reprovisioned everything but this is a production environment where downtime is not an option. In addition the PIP will also change and some end-users are whitelisting the IP in their firewalls.

**Comment by svickers** [comment]
The workaround stopped working for a us a couple weeks ago.  We've just bit the bullet and recreated the environment from scratch and migrated all the apps. Painful to do but gave us an opportunity to get everything codified in bicep.  The support ticket has been escalated but nothing of substance to report back.
