### ISSUE TITLE
Access to KeyVault (permission fails) after initially working using Managed Identity

### ISSUE THREAD

**Issue by elmo61** [microsoft/azure-container-apps#1124]
- [x] bug report
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

This is for Azure Container jobs in a  .net 8.0 c# Project

### Issue description
After turning on managed Identity for the Container Job and using that Identity to give access to a given keyvault. The job can successfully access that keyvault on each of its runs, until a change is made to the job (such as new docker image is deployed or changes to scale rules)

From that point onwards that job will always fail on start-up until the identity is turned off and back on (to create a new one) and then readded to the keyvault permissions. 

### Steps to reproduce
1. Create a .NET 8.0 container job project which uses keyvault to load its secrets

```var azureServiceTokenProvider = new AzureServiceTokenProvider();
var keyVaultClient = new KeyVaultClient(
    new KeyVaultClient.AuthenticationCallback(
        azureServiceTokenProvider.KeyVaultTokenCallback));

configuration = new ConfigurationBuilder()
    .AddConfiguration(configuration)
    .AddAzureKeyVault(
        $"https://{configuration["KeyVaultName"]}.vault.azure.net/",
        keyVaultClient,
        new DefaultKeyVaultSecretManager())
    .Build();
```

3. Deploy to azure container jobs.
4. Enable managed identity for the job
5. Add identity to keyvault permissions
6. Run job to show it successfully working
7. Edit scale rules or deploy a new registry (or sometimes just leave it a day)
8. Run job again and see it fails with the following errors

```
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.microsoftonline.com/e2458d43-9af5-4562-86b3-2056da5b537e. Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.microsoftonline.com/e2458d43-9af5-4562-86b3-2056da5b537e. Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. MSI ResponseCode: Unauthorized, Response: {"type":"https://tools.ietf.org/html/rfc7235#section-3.1","title":"Unauthorized","status":401,"traceId":"00-8002cdbf016106bcd30e57c114381c3a-c15e056f1646bcda-00"}
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.microsoftonline.com/e2458d43-9af5-4562-86b3-2056da5b537e. Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Environment variable LOCALAPPDATA not set.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.microsoftonline.com/e2458d43-9af5-4562-86b3-2056da5b537e. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired.
Unhandled exception. Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.microsoftonline.com/e2458d43-9af5-4562-86b3-2056da5b537e. Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.microsoftonline.com/e2458d43-9af5-4562-86b3-2056da5b537e. Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. MSI ResponseCode: Unauthorized, Response: {"type":"https://tools.ietf.org/html/rfc7235#section-3.1","title":"Unauthorized","status":401,"traceId":"00-cc80c7cbd7208719b0ee52d200df8f6c-3eeb9150d6a8bcbc-00"}
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.microsoftonline.com/e2458d43-9af5-4562-86b3-2056da5b537e. Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Environment variable LOCALAPPDATA not set.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.microsoftonline.com/e2458d43-9af5-4562-86b3-2056da5b537e. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. /bin/bash: az: No such file or directory
at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAccessTokenAsyncImpl(String authority, String resource, String scope)
at Microsoft.Azure.KeyVault.KeyVaultCredential.PreAuthenticate(Uri url)
at Microsoft.Azure.KeyVault.KeyVaultCredential.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretsWithHttpMessagesAsync(String vaultBaseUrl, Nullable`1 maxresults, Dictionary`2 customHeaders, CancellationToken cancellationToken)
at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretsAsync(IKeyVaultClient operations, String vaultBaseUrl, Nullable`1 maxresults, CancellationToken cancellationToken)
at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.LoadAsync()
at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.Load()
at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
at RasterizerContainerJob.Program.<Main>(String[] args)
```

**Expected behavior** [What you expected to happen.]
The permissions to continue to work and keyvault authenicates fine

**Actual behavior** [What actually happened.]
The jobs start failing with a forbidden error

### Additional context
Creating of the jobs was via Portal. Project is deployed to azure registry via Azure Devops

**Comment by vturecek** [comment]
@elmo61 The `Microsoft.Azure.KeyVault` package you're using is deprecated and hasn't had an update in about 5 years. I verified that managed identity is available in Container App Job runs consistently after updating the job spec, so my hunch is that there is an issue with the way Microsoft.Azure.KeyVault is getting tokens. 

Can you try updating to the support Key Vault library by following this migration guide: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Secrets/MigrationGuide.md
