### ISSUE TITLE
Cannot connect/read logs of a working Container App

### ISSUE THREAD

**Issue by CezaryKlus** [microsoft/azure-container-apps#1299]
### This issue is a:
- [x ] bug report -> please search issues before submitting

### Issue description
1. Cannot connect to a working Container App:
* From Portal
![image](https://github.com/user-attachments/assets/713177da-828e-488f-beb5-8884946a202c)
* From console
`
The command failed with an unexpected error. Here is the traceback:
Handshake status 401 Unauthorized
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 666, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 703, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 336, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/containerapp/custom.py", line 3525, in containerapp_ssh
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/containerapp/_ssh_utils.py", line 61, in __init__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\websocket/_core.py", line 253, in connect
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\websocket/_handshake.py", line 57, in handshake
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\websocket/_handshake.py", line 148, in _get_resp_headers
websocket._exceptions.WebSocketBadStatusException: Handshake status 401 Unauthorized
`
2. Cannot read log stream in Portal of another working (all green) Container App, neither Console nor System
![image](https://github.com/user-attachments/assets/7f163bf6-2164-487d-9ded-5f553920ce9f)

3. az logout/login performed. Refreshed credentials in Azure Portal. Didn't help

This affects the whole environment in West Europe

**Comment by admsallai** [comment]
I have the same issue

**Comment by v-vish** [comment]
@CezaryKlus Hi...We have just replicated this from our end and it worked for us. Could you please retest and confirm.

**Comment by CezaryKlus** [comment]
@v-vish it started to work but I would like to know that this won't happen again if ACA considers itself to be a production-grade platform. Thanks

**Comment by simonjj** [comment]
Thank you for continuing to report these issues. We've identified a potential issue and are continuing to investigate.

**Comment by simonjj** [comment]
@naveensky can you please share your environment and app details via acasupport at microsoft.com and reference this issue in the email please?

**Comment by simonjj** [comment]
We've identified the issue and have a fix. This will be deployed in the coming days and should be available globally by November 7th.

**Comment by DaHaiz** [comment]
experiencing this since a 1-2 weeks. eu-west. have filed a azure support ticket. applies to container logs, container apps environment system log, console access. for each and every container apps environment i have deployed (about 5). this is an urgent issue imo and needs to be fixed as soon as anyhow possible.

**Comment by edwardfward** [comment]
Same issue the last four days in Azure US Government

**Comment by simonjj** [comment]
@edwardfward thanks for raising this issue with us. The gateway for these real-time calls is a shared component on a per-region basis, so there can be periods of congestion but what you're reporting seems indeed off. Would you be so kind as to send us an email to acasupport at microsoft.com with your subscription/environment and app name please.

**Comment by simonjj** [comment]
@edwardfward can you please share if this issue is still impacting you and ping us at acasupport please?

**Comment by rybnico** [comment]
I am currently experiencing the same error in westeurope. It worked 2 hours ago, now I get "Failed to connect to replica.

I found this error in the JS console:
`WebSocket connection to 'wss://westeurope.azurecontainerapps.dev/subscriptions/***/resourceGroups/***/containerApps/toolbox/revisions/toolbox--2/replicas/toolbox--2-*-*/containers/toolbox/exec...' failed:`

**Comment by Agazoth** [comment]
I am experiencing the issue right now. 401 when trying to open Log Stream in the protal, but the app runs as expected:

![Image](https://github.com/user-attachments/assets/f4dfdb6f-6abc-485d-81b6-9b0acbf40a87)

**Comment by trescst** [comment]
We are experiencing the same issue as @Agazoth currently: 401 Unauthorized when trying to check the logs (app also runs without issues, logs are visible through Log Analytics).

**Comment by dsbahr** [comment]
We are also experiencing this issue.But from I can see this only happens on our container app environments in westeurope. Northeurope seems to work.

**Comment by Agazoth** [comment]
Now it works again

**Comment by markolukicic** [comment]
I confirm that it works again.

**Comment by Agazoth** [comment]
Hm, error is back ...

**Comment by markolukicic** [comment]
Ugh,,, at least we know it is on Microsoft side.

**Comment by dsbahr** [comment]
I'm experiencing the issue again.

**Comment by tomiasp** [comment]
Same here...

**Comment by reegan-anne** [comment]
Still experiencing in all regions. Very inconsistent that the console doesn't work 80% of the time

**Comment by booooza** [comment]
Same here

**Comment by megabus-tobin** [comment]
We are encountering this currently on any container app running in australiaeast. Was working fine recently (a day or so ago). Both log streaming and console connections fail with a 401 error, just as others have experienced.

**Comment by tnabil** [comment]
Also having the same issue right now in Australia East. Was working a few days ago.

**Comment by felixwee** [comment]
Also facing issue now in Australia East.

**Comment by SteveyblamWork** [comment]
Same in UK south as of today

**Comment by fvelcker** [comment]
Just to add one more. UKsouth here.

**Comment by sknzl** [comment]
One more in UKsouth. Started today

**Comment by dcraig-datacom** [comment]
Still encountering this error in Australia East as of now!

Edit: It was working a couple of days ago as others have mentioned.

`az containerapp exec ....` throws this error:

```
The command failed with an unexpected error. Here is the traceback:
Handshake status 401 Unauthorized
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 666, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 734, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 703, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 336, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 120, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/containerapp/custom.py", line 3524, in containerapp_ssh
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/containerapp/_ssh_utils.py", line 61, in __init__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\websocket/_core.py", line 253, in connect
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\websocket/_handshake.py", line 57, in handshake
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\websocket/_handshake.py", line 148, in _get_resp_headers
websocket._exceptions.WebSocketBadStatusException: Handshake status 401 Unauthorized
```
