### ISSUE TITLE
Set Traffic Weight via CLI: Invalid JSON error and does not set weight

### ISSUE THREAD

**Issue by michaelmcneilnet** [microsoft/azure-container-apps#219]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When using the CLI to change the traffic weight of a revision, we now get an error message and the weight is not changed. We are using v0.3.4 of the CLI.

```
az containerapp ingress traffic set -n XXX -g XXX --revision-weight "XXX=100"
Invalid JSON: Expected end of string, but instead reached end of data. LineNumber: 0 | BytePositionInLine: 4096.
```

We have also tried with the now-deprecated `--traffic-weight` flag and get the same error result.

**Comment by kendallroden** [comment]
Thanks for reporting. Will get back to you

**Comment by panchagnula** [comment]
@haroonf can you take a look at this - might be a regression from the recent revision changes?

**Comment by haroonf** [comment]
Could you run the same command with --debug? Can't seem to reproduce. Thanks

**Comment by michaelmcneilnet** [comment]
> Could you run the same command with --debug? Can't seem to reproduce. Thanks

Sure, is there a good way to send you the output? It has a lot of subscription and resource ids etc which I don't want to post publicly.

**Comment by anthonychu** [comment]
@michaelmcneilnet Not sure if there's a better way, but if you want to email it as a text file to me at antchu @ microsoft.com, I can relay it to @panchagnula and team. Please redact any info that you don't want to share.

The 4096 number is curious as that's 4KB. Might be hitting some sort of size limit in an API response. The debug logs will be helpful.

**Comment by michaelmcneilnet** [comment]
@anthonychu Emailed that across now 👍

**Comment by anthonychu** [comment]
Thanks. We've identified the issue (API request exceeded 4KB) and are investigating a fix.

**Comment by anthonychu** [comment]
The `traffic` array has a lot of items in there and that caused the request payload to exceed the current limit of 4096B. Since a lot of them have a weight of 0, you can manually clear them for now while we work on a fix in the service and/or the CLI.

You can do this with ARM or bicep, or use YAML with the CLI:

- `az containerapp show -n $APP -g $GROUP -o yaml > app.yaml`

- In app.yaml, remove items in the `traffic` array that have a weight of 0.

- `az containerapp update -n $APP -g $GROUP --yaml app.yaml`

**Comment by michaelmcneilnet** [comment]
> The `traffic` array has a lot of items in there and that caused the request payload to exceed the current limit of 4096B. Since a lot of them have a weight of 0, you can manually clear them for now while we work on a fix in the service and/or the CLI.
> 
> You can do this with ARM or bicep, or use YAML with the CLI:
> 
> * `az containerapp show -n $APP -g $GROUP -o yaml > app.yaml`
> * In app.yaml, remove items in the `traffic` array that have a weight of 0.
> * `az containerapp update -n $APP -g $GROUP --yaml app.yaml`

I tried this and get the following error from the CLI. I then tried skipping your middle step, so uploading the yaml file exactly as it was downloaded, and same issue occurs.

```
The command failed with an unexpected error. Here is the traceback:
unacceptable character #x0000: special characters are not allowed
  in "app.yaml", position 3
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "C:\Users\micha\.azure\cliextensions\containerapp\azext_containerapp\_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\micha\.azure\cliextensions\containerapp\azext_containerapp\custom.py", line 697, in update_containerapp
    return update_containerapp_logic(cmd,
  File "C:\Users\micha\.azure\cliextensions\containerapp\azext_containerapp\custom.py", line 509, in update_containerapp_logic
    return update_containerapp_yaml(cmd=cmd, name=name, resource_group_name=resource_group_name, file_name=yaml, no_wait=no_wait, from_revision=from_revision)
  File "C:\Users\micha\.azure\cliextensions\containerapp\azext_containerapp\custom.py", line 121, in update_containerapp_yaml
    yaml_containerapp = process_loaded_yaml(load_yaml_file(file_name))
  File "C:\Users\micha\.azure\cliextensions\containerapp\azext_containerapp\custom.py", line 97, in load_yaml_file
    return yaml.safe_load(stream)
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/__init__.py", line 125, in safe_load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/__init__.py", line 79, in load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/loader.py", line 34, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/reader.py", line 85, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/reader.py", line 135, in determine_encoding
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/reader.py", line 169, in update
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/reader.py", line 143, in check_printable
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "app.yaml", position 3
  ```

**Comment by michaelmcneilnet** [comment]
> The `traffic` array has a lot of items in there and that caused the request payload to exceed the current limit of 4096B. Since a lot of them have a weight of 0, you can manually clear them for now while we work on a fix in the service and/or the CLI.
> 
> You can do this with ARM or bicep, or use YAML with the CLI:
> 
> * `az containerapp show -n $APP -g $GROUP -o yaml > app.yaml`
> * In app.yaml, remove items in the `traffic` array that have a weight of 0.
> * `az containerapp update -n $APP -g $GROUP --yaml app.yaml`

Thanks, I ran this but all of our revisions still show in the portal. I was expecting all of them except the latest few I kept in the yaml file to remain. Does it not work like that?

**Comment by michaelmcneilnet** [comment]
@anthonychu Hi, any update on the above question about the workaround? Our automated deployments fail everytime because of this and the workaround appeared to have no effect

**Comment by michaelmcneilnet** [comment]
This looks to be working correctly now, has a fix been deployed?
