### ISSUE TITLE
Spring Boot / az cli Key Vault user assigned identity - response 400 or 405 method not allowed

### ISSUE THREAD

**Issue by anrub** [microsoft/azure-container-apps#341]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

I want to use user assigned identity to access key vault. Somehow I can't access the vault, as it is unsuccessful to get a token.

Request:
http://localhost:42356/msi/token?resource=https%3A%2F%2Fvault.azure.net&api-version=2017-09-01&clientid=xxx-xxxx-xx

### Steps to reproduct
1. Create user assigned identity and attach to capps, assign policy to key vault
2. try to login with identity to access keyvault
3. or try to login in container with azure cli

**Expected behavior** 
Token is generated, key vault is accessed.

**Actual behavior** 

Token can't be generated and throws an error 400 / 405 on the localhost-msi call.

### Additional context
When I try to use the spring boot keyvault starter to access the keyvault:

````
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://localhost:42356/msi/token?resource=https%3A%2F%2Fvault.azure.net&api-version=2017-09-01&clientid=xxx
````

With a newer version of the library:
````
Server returned HTTP response code: 400 for URL: http://localhost:42356/msi/token?resource=https%3A%2F%2Fvault.azure.net&api-version=2019-08-01&client_id=xxxxx"       
````

When I try to login with the azure cli in the container via console:

````
# az login --identity -u xxxxxx
The command failed with an unexpected error. Here is the traceback:

405 Client Error: Method Not Allowed for url: http://localhost:42356/msi/token
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/profile/custom.py", line 128, in login
    return profile.find_subscriptions_in_vm_with_msi(username, allow_no_subscriptions)
  File "/usr/lib/python3/dist-packages/azure/cli/core/_profile.py", line 305, in find_subscriptions_in_vm_with_msi
    msi_creds = MSIAuthentication(resource=resource, client_id=identity_id)
  File "/usr/lib/python3/dist-packages/msrestazure/azure_active_directory.py", line 592, in __init__
    self.set_token()
  File "/usr/lib/python3/dist-packages/msrestazure/azure_active_directory.py", line 598, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
  File "/usr/lib/python3/dist-packages/msrestazure/azure_active_directory.py", line 486, in get_msi_token
    result.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: http://localhost:42356/msi/token
````

**Comment by anthonychu** [comment]
The library used to integrate with managed identity appears to be using an old api version to call the managed identity endpoint (2017-09-01) which I believe is not supported by Container Apps. Related: https://github.com/microsoft/azure-container-apps/issues/297#issuecomment-1178056458

**Comment by anrub** [comment]
Then it looks like the current version of [spring cloud azure](https://microsoft.github.io/spring-cloud-azure) is not supporting this API versio of capps. Maybe https://github.com/Azure/azure-sdk-for-java/issues/30043 is related.

Even if I update to the latest 4.3.3, it tries to use 2017 API.

**Comment by anthonychu** [comment]
@vturecek Do you know what might be happening here?

**Comment by anrub** [comment]
I made a sample application, that works in appservice and throws an error in container apps: https://github.com/anrub/azure-spring-boot with the docker image: [ghcr.io/anrub/azdemo:2](https://github.com/users/anrub/packages/container/azdemo/32900871?tag=2). Needs a few env vars, see [README](https://github.com/anrub/azure-spring-boot/blob/master/README.md), tries to read testKey from the configured keyvault.

**Comment by vturecek** [comment]
@anrub just as a sanity check, can you confirm that you are using the correct Client ID for the user-assigned identity?

**Comment by anrub** [comment]
@vturecek nice, somehow I put in the principal_id instead of the client_id, don't know how I could have missed that

**Comment by vturecek** [comment]
@anrub happens to me all the time, glad it was an easy fix!
