### ISSUE TITLE
Dapr timeout : Scale 0-1

### ISSUE THREAD

**Issue by sf-declanomalley** [microsoft/azure-container-apps#369]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
the dapr sidecar sometimes fails to spin up successfully when the application scales to 0. we sometimes find we are getting errors calling the sidecar (timeouts) and the only way to get the application to work successfully is to redeploy to effectively run a restart or set minimum scale to 1, costing us more as they are always up when not required.

### Steps to reproduce
1. deploy an application that calls the sidecar, i.e to grab state
2. configure container apps min scale to 0
3. wait for application to scale to 0, make a request to the application and you will receive timeout

**Expected behavior** [What you expected to happen.]
the sidecar to spin up when the application scales to 1 and make  the request as expected

**Actual behavior** [What actually happened.]
the sidecar is not spinning up

**Screenshots**         

### Additional context
i can see that the dapr component hasn't been initialised today under the ContainerAppSystemLogs_CL log
the ContainerAppConsoleLogs_CL log contains:
```
--- End of inner exception stack trace ---
at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs , ValueTask , CancellationToken )
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 )
at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String , Int32 , HttpRequestMessage , Boolean , CancellationToken )
at Dapr.Client.DaprClientGrpc.GetStateAsync[TValue](String storeName, String key, Nullable`1 consistencyMode, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken )
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
--- End of stack trace from previous location ---
at Program.<>c.<<<Main>$>b__0_3>d.MoveNext() in /src/Program.cs:line 66
at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken )
at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String , Int32 , HttpRequestMessage , Boolean , CancellationToken )
---> System.Net.Sockets.SocketException (111): Connection refused
at AMethod(Guid claimId, Boolean getClaimForm) in /code.cs:line 88
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage , Boolean , CancellationToken )
Dapr.DaprException: State operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage )
at Microsoft.AspNetCore.Http.RequestDelegateFactory.<ExecuteTask>g__ExecuteAwaited|58_0[T](Task`1 task, HttpContext httpContext)
at Storage.Get(Guid claimId) in Storage.cs:line 34
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]
Connection id "0HMK1K7PJSDQ4", Request id "0HMK1K7PJSDQ4:00000002": An unhandled exception was thrown by the application.
at Dapr.Client.DaprClientGrpc.GetStateAsync[TValue](String storeName, String key, Nullable`1 consistencyMode, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage , Boolean , CancellationToken )
---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Connection refused (127.0.0.1:50001) SocketException: Connection refused", DebugException="System.Net.Http.HttpRequestException: Connection refused (127.0.0.1:50001)
at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken )


```

**Comment by kendallroden** [comment]
Hi @sf-declanomalley is this still occurring? I want to make sure we properly investigate.
