### ISSUE TITLE
az containerapp update with --no-wait throws an exception

### ISSUE THREAD

**Issue by SeanErvinson** [microsoft/azure-container-apps#630]
Command
```
az containerapp update --no-wait -n <container-name> -g <resource-group> --image <image> --debug
```

Errors:
```
INFO: cli.azure.cli.core.util: Request URL: 'https://management.azure.com/subscriptions/***/resourceGroups/*redacted*/providers/Microsoft.App/containerApps/sample-weather-aca?api-version=2022-06-01-preview'
INFO: cli.azure.cli.core.util: Request method: 'PATCH'
INFO: cli.azure.cli.core.util: Request headers:
INFO: cli.azure.cli.core.util:     'User-Agent': 'python/3.10.8 (Linux-5.15.0-1031-azure-x86_64-with-glibc2.31) AZURECLI/2.44.1 (DEB) '
INFO: cli.azure.cli.core.util:     'Accept-Encoding': 'gzip, deflate'
INFO: cli.azure.cli.core.util:     'Accept': '*/*'
INFO: cli.azure.cli.core.util:     'Connection': 'keep-alive'
INFO: cli.azure.cli.core.util:     'x-ms-client-request-id': '4c3e2feb-6d41-4b5d-9a9f-7c253b4ae1f7'
INFO: cli.azure.cli.core.util:     'Content-Type': 'application/json'
INFO: cli.azure.cli.core.util:     'CommandName': 'containerapp update'
INFO: cli.azure.cli.core.util:     'ParameterSetName': '--no-wait -n -g --image --debug'
INFO: cli.azure.cli.core.util:     'Authorization': '***'
INFO: cli.azure.cli.core.util:     'Content-Length': '244'
INFO: cli.azure.cli.core.util: Request body:
INFO: cli.azure.cli.core.util: {"properties": {"template": {"containers": [{"image": "nonprodplatformsharedcr.azurecr.io/sample-weather:4179208403", "name": "sampleweatherapp", "resources": {"cpu": 0.5, "memory": "1Gi", "ephemeralStorage": "3Gi"}}], "revisionSuffix": null}}}
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
DEBUG: urllib3.connectionpool: https://management.azure.com:443 "PATCH /subscriptions/***/resourceGroups/*redacted*/providers/Microsoft.App/containerApps/sample-weather-aca?api-version=2022-06-01-preview HTTP/1.1" 202 0
INFO: cli.azure.cli.core.util: Response status: 202
INFO: cli.azure.cli.core.util: Response headers:
INFO: cli.azure.cli.core.util:     'Cache-Control': 'no-cache'
INFO: cli.azure.cli.core.util:     'Pragma': 'no-cache'
INFO: cli.azure.cli.core.util:     'Expires': '-1'
INFO: cli.azure.cli.core.util:     'Location': 'https://management.azure.com/subscriptions/***/providers/Microsoft.App/locations/*redacted*/containerappOperationResults/d5598dd0-977e-4a44-8c4b-61bffe752498?api-version=2022-06-01-preview'
INFO: cli.azure.cli.core.util:     'Retry-After': '5'
INFO: cli.azure.cli.core.util:     'api-supported-versions': '2022-01-01-preview, 2022-03-01, 2022-06-01-preview, 2022-10-01, 2022-11-01-preview, 2023-02-01'
INFO: cli.azure.cli.core.util:     'Server': 'Microsoft-IIS/10.0'
INFO: cli.azure.cli.core.util:     'X-Powered-By': 'ASP.NET'
INFO: cli.azure.cli.core.util:     'x-ms-ratelimit-remaining-subscription-resource-requests': '499'
INFO: cli.azure.cli.core.util:     'x-ms-request-id': 'ccbe96dc-abaf-40b3-92ab-3d3468afd8e3'
INFO: cli.azure.cli.core.util:     'x-ms-correlation-request-id': 'ccbe96dc-abaf-40b3-92ab-3d3468afd8e3'
INFO: cli.azure.cli.core.util:     'x-ms-routing-request-id': 'EASTUS:20230215T003131Z:ccbe96dc-abaf-40b3-92ab-3d3468afd8e3'
INFO: cli.azure.cli.core.util:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
INFO: cli.azure.cli.core.util:     'X-Content-Type-Options': 'nosniff'
INFO: cli.azure.cli.core.util:     'Date': 'Wed, 15 Feb 2023 00:31:30 GMT'
INFO: cli.azure.cli.core.util:     'Content-Length': '0'
INFO: cli.azure.cli.core.util: Response content:
INFO: cli.azure.cli.core.util: 
DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py", line 923, in update_containerapp
    return update_containerapp_logic(cmd=cmd,
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py", line 894, in update_containerapp_logic
    handle_raw_exception(e)
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_client_factory.py", line 54, in handle_raw_exception
    raise e
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py", line 886, in update_containerapp_logic
    r = ContainerAppClient.update(
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_clients.py", line 119, in update
    return r.json()
  File "/opt/az/lib/python3.10/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/az/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/az/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/az/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 
ERROR: cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
ERROR: az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
ERROR: cli.azure.cli.core.azclierror: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py", line 923, in update_containerapp
    return update_containerapp_logic(cmd=cmd,
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py", line 894, in update_containerapp_logic
    handle_raw_exception(e)
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_client_factory.py", line 54, in handle_raw_exception
    raise e
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py", line 886, in update_containerapp_logic
    r = ContainerAppClient.update(
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_clients.py", line 119, in update
    return r.json()
  File "/opt/az/lib/python3.10/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/az/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/az/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/az/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR: az_command_data_logger: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py", line 923, in update_containerapp
    return update_containerapp_logic(cmd=cmd,
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py", line 894, in update_containerapp_logic
    handle_raw_exception(e)
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_client_factory.py", line 54, in handle_raw_exception
    raise e
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py", line 886, in update_containerapp_logic
    r = ContainerAppClient.update(
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_clients.py", line 119, in update
    return r.json()
  File "/opt/az/lib/python3.10/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/az/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/az/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/az/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fcf7a01c940>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 7.507 seconds (init: 0.384, invoke: 7.123)
INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
INFO: telemetry.client: Accumulated 0 events. Flush the clients.
INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
INFO: telemetry.save: Save telemetry record of length 6923 in cache
WARNING: telemetry.check: Negative: The /home/runner/.azure/telemetry.txt was modified at 2023-02-15 00:30:28.590219, which in less than 600.000000 s
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fc973714940>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 31.956 seconds (init: 0.386, invoke: 31.570)
INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
INFO: telemetry.client: Accumulated 0 events. Flush the clients.
INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
INFO: telemetry.save: Save telemetry record of length 3450 in cache
WARNING: telemetry.check: Negative: The /home/runner/.azure/telemetry.txt was modified at 2023-02-15 00:30:28.590219, which in less than 600.000000 s
```

### Issue description
When I try to update the container app without the --no-wait options everything works fine but whenever I include the --no-wait-option I get this error. The update still does go through but it throws this exception.

### Steps to reproduce
1. az containerapp update -n {container-name} -g {resource-group} --image {image} ← this command works fine
2. az containerapp update --no-wait  -n {container-name} -g {resource-group} --image {image} ← this throws an exception

**Expected behavior** [What you expected to happen.]
It should just exit gracefully.

**Actual behavior** [What actually happened.]
Throws an exception even though the update went through.

### Additional context
Via Az CLI v 2.44.1
Running on the latest extension version 0.3.21 (I also tried downgrading to 0.3.17 also the same error).

Edit: fix command arguments

**Comment by simonjj** [comment]
This should be fixed now. Closing.
