### ISSUE TITLE
`az containerapp update` yielded back "Remote end closed connection without response"

### ISSUE THREAD

**Issue by onionhammer** [microsoft/azure-container-apps#661]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I attempted to update a container app via CLI and received the following error:

```
/ Running ..
| Running ..
\ Running ..
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/az/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/opt/az/lib/python3.10/http/client.py", line 3[18](https://github.com/crfusa/c2c-exchange/actions/runs/4376282564/jobs/7658198474#step:5:19), in begin
    version, status, reason = self._read_status()
  File "/opt/az/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/az/lib/python3.10/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/az/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/az/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/opt/az/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/opt/az/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 1[21](https://github.com/crfusa/c2c-exchange/actions/runs/4376282564/jobs/7658198474#step:5:22), in handler
    return op(**command_args)
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py", line 9[25](https://github.com/crfusa/c2c-exchange/actions/runs/4376282564/jobs/7658198474#step:5:26), in update_containerapp
    return update_containerapp_logic(cmd=cmd,
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py", line 896, in update_containerapp_logic
    handle_raw_exception(e)
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_client_factory.py", line 54, in handle_raw_exception
    raise e
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py", line 888, in update_containerapp_logic
    r = ContainerAppClient.update(
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_clients.py", line 1[31](https://github.com/crfusa/c2c-exchange/actions/runs/4376282564/jobs/7658198474#step:5:32), in update
    return poll(cmd, request_url, "inprogress")
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_clients.py", line 71, in poll
    raise e
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_clients.py", line 56, in poll
    r = send_raw_request(cmd.cli_ctx, "GET", request_url)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/util.py", line 1003, in send_raw_request
    r = s.send(prepped, **settings)
  File "/opt/az/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/requests/adapters.py", line [49](https://github.com/crfusa/c2c-exchange/actions/runs/4376282564/jobs/7658198474#step:5:50)8, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

### Steps to reproduce
1. Run az containerapp update

**Expected behavior** [What you expected to happen.]
It shouldnt crash

**Actual behavior** [What actually happened.]
It crashed, maybe 1 in 5 deployments I have slowness, but this is the first time I've seen  an outright failure like this.

**Screenshots**         

### Additional context
CLI in github action

**Comment by SophCarp** [comment]
Hi @onionhammer thanks for submitting! Can you submit a support ticket? We need your app details to investigate this issue.

**Comment by onionhammer** [comment]
@SophCarp created ticket 2303090040009677

**Comment by SophCarp** [comment]
We've investigated the issue and logged an internal bug (# 17698618).

**Comment by simonjj** [comment]
@onionhammer, closing this as there have been many releases of the extension and now main CLI since. Back in March of '23 we needed a --debug run to do more investigation. If this issue persists and you get a chance please reopen and update us.
