### ISSUE TITLE
Getting error on AZ CLI while deploying Container Apps via BICEP

### ISSUE THREAD

**Issue by ractando** [microsoft/azure-container-apps#789]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When I try to deploy my container app setup via a BICEP file, the AZ CLI gives me error stating "**[WinError 193] %1 is not a valid Win32 application**", The version of AZ CLI is up to date on my system.

![image](https://github.com/microsoft/azure-container-apps/assets/17726651/7fe59bb0-a3e0-4bd2-a857-1369186d0830)

### Steps to reproduce
1. .. Create a Bicep file for deploying CA.
2. .. Run it via az cli using this command 
_az deployment group create --resource-group "yourresourcegroupname" --template-file containerapps.bicep --parameters location="yourregionofchoice"_
3. Running the command with --debug gives me this.

```
C:\Users\rachittandon\Desktop>az deployment group create --resource-group "rg-Abc-test" --template-file containerapps.bicep --parameters location="West Europe" --debug
cli.knack.cli: Command arguments: ['deployment', 'group', 'create', '--resource-group', 'rg-Abc-test', '--template-file', 'containerapps.bicep', '--parameters', 'location=West Europe', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0178A460>, <function OutputProducer.on_global_arguments at 0x01858BF8>, <function CLIQuery.on_global_arguments at 0x01877850>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'deployment': ['azure.cli.command_modules.resource']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: reso
[containerappbicep.txt](https://github.com/microsoft/azure-container-apps/files/11752463/containerappbicep.txt)
urce                  0.016        47       209
cli.azure.cli.core: Total (1)                 0.016        47       209
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 47 groups, 209 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : deployment group create
cli.azure.cli.core: Command table: deployment group create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03B4B460>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\rachittandon\.azure\commands\2023-06-15.09-03-35.deployment_group_create.7352.log'.
az_command_data_logger: command args: deployment group create --resource-group {} --template-file {} --parameters {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03B73928>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03B8D898>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03B8DA90>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01858C40>, <function CLIQuery.handle_query_parameter at 0x01877898>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03B8DA48>]
cli.azure.cli.command_modules.resource._bicep: Current value of "use_binary_from_path": if_found_in_ci.
cli.azure.cli.command_modules.resource._bicep: Bicep CLI installation path: C:\Users\rachittandon\.azure\bin\bicep.exe
cli.azure.cli.command_modules.resource._bicep: Bicep CLI installed: True.
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 546, in deploy_arm_template_at_resource_group
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 575, in _deploy_arm_template_at_resource_group
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 989, in _prepare_deployment_properties_unmodified
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 94, in run_bicep_command
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 273, in _get_bicep_installed_version
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 311, in _run_command
  File "subprocess.py", line 503, in run
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1440, in _execute_child
OSError: [WinError 193] %1 is not a valid Win32 application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 109, in handle_template_based_exception
AttributeError: 'OSError' object has no attribute 'inner_exception'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 114, in handle_template_based_exception
knack.util.CLIError: [WinError 193] %1 is not a valid Win32 application

cli.azure.cli.core.azclierror: [WinError 193] %1 is not a valid Win32 application
az_command_data_logger: [WinError 193] %1 is not a valid Win32 application
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03B4B580>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.943 seconds (init: 0.454, invoke: 0.490)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3489 in cache
telemetry.check: Negative: The C:\Users\rachittandon\.azure\telemetry.txt was modified at 2023-06-15 08:57:48.325351, which in less than 600.000000 s
```

**Expected behavior** [What you expected to happen.]
CA should deploy successfully

**Actual behavior** [What actually happened.]
An error occurs as specified above

**Screenshots**         
Bicep file and Screenshot attached
![image](https://github.com/microsoft/azure-container-apps/assets/17726651/763dd054-bb8c-424b-8b85-ed9cd8415894)

**Comment by dariagrigoriu** [comment]
Please share the Bicep file if possible.

**Comment by anthonychu** [comment]
Possibly related to: https://github.com/Azure/bicep/issues/2364

@ractando please try reinstalling your Bicep and Azure CLI.
