### ISSUE TITLE
Container Apps Revisions goes away after adding Route Table to subnet

### ISSUE THREAD

**Issue by mnadeem** [microsoft/azure-container-apps#881]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Container Apps in Subnet with RouteTable does not work

### Steps to reproduce
1. Create Vnet Subnet
2. Create Container Apps, it works
3. Add Route table to Subnet, Revisions goes away
4. Remove Route table, Revisions comes back.

**Expected behavior** [Route Table should not affect Container app]: Or is there a way to make it work with Route table

**Actual behavior** [Container Apps Revisions goes away and can't be created]

**Screenshots**         

Revisions goes away after adding Route Table to subnet 

![image](https://github.com/microsoft/azure-container-apps/assets/476145/84b1f5ef-cb2a-42df-84c5-9f3de27df459)

Revisions automatically comes back after removing route table from subnet

### Additional context
This issue seems to be related to https://github.com/microsoft/azure-container-apps/issues/522

**Comment by howang-ms** [comment]
Hi @mnadeem
It seems you are using the Consumption only environment, which doesn't support UDR. Can you please have a try on Workload Profile Environment? 

More detail can be found at https://learn.microsoft.com/en-us/azure/container-apps/networking?tabs=azure-cli#environment-selection

**Comment by mnadeem** [comment]
Is this generally available in centralus region?

**Comment by mnadeem** [comment]
`az containerapp env workload-profile add --resource-group app-dev-rg --name app-dev-cae --workload-profile-name app-dev-cae-wlp  --workload-profile-type D4 --min-nodes 2 --max-nodes 3`

Getting the following error

```
Command group 'containerapp env workload-profile' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\mnadeem6\.azure\cliextensions\containerapp\azext_containerapp\custom.py", line 5215, in add_workload_profile
    workload_profiles_lower = [p["name"].lower() for p in workload_profiles]
TypeError: 'NoneType' object is not iterable
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```

**Comment by mnadeem** [comment]
```
az --version
azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
application-insights              0.1.19
containerapp                      0.3.37

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\user\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by ChristopheLux** [comment]
Hello

We did encounter this issue on a recent deployment of a container App Environment
All configuration have been done as per the documentation. 

Any progress on this
Fell free to ask for any configuration information

KInd Regards
